import {StrictMode,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";

type Screen="today"|"history"|"settings";
const samples=[{date:"Tuesday, September 29",mood:"Steady",text:"Took a gentle walk and felt more settled by the afternoon.",tag:"Movement"},{date:"Monday, September 28",mood:"Tender",text:"A quiet day. Noticed that rest helped my energy return.",tag:"Rest"}];
function Nav({active,label,icon,onClick}:{active:boolean;label:string;icon:string;onClick:()=>void}){return <button className={`nav ${active?"active":""}`} onClick={onClick} aria-current={active?"page":undefined}><span>{icon}</span>{label}</button>}
function Today(){const [saved,setSaved]=useState(false);return <><section className="hero"><div><p className="kicker">Today</p><h1>How are you feeling?</h1><p>A few words are enough. This is your space to be honest and unhurried.</p></div><div className="date"><small>SEP</small><b>30</b><small>2026</small></div></section><section className="grid"><article className="card note"><header><div><h2>Daily note</h2><p>Write freely. Your words stay on this device.</p></div><span className="preview">Synthetic preview</span></header><label className="sr" htmlFor="note">Daily journal note</label><textarea id="note" defaultValue="I woke up feeling curious about the day. " onChange={()=>setSaved(false)} placeholder="What would you like to remember about today?"/><footer><span>Nothing leaves this Mac.</span><button className="primary" onClick={()=>setSaved(true)}>{saved?"Saved locally":"Save note"}</button></footer></article><aside className="card check"><header><div><h2>Gentle check-in</h2><p>Optional, no right answers.</p></div><span>✦</span></header><label htmlFor="mood">Mood</label><select id="mood" defaultValue="steady"><option value="steady">Steady</option><option>Tender</option><option>Energized</option><option>Low</option></select><label htmlFor="energy">Energy <em>0–10</em></label><input id="energy" type="range" min="0" max="10" defaultValue="6"/><div className="range"><span>Low</span><span>6</span><span>High</span></div><label htmlFor="sleep">Sleep</label><div className="hours"><input id="sleep" type="number" min="0" max="24" step=".5" placeholder="—"/><span>hours</span></div><p className="future">◌ Menstrual Period tracking will be added later.</p></aside></section><p className="privacy">⌑ Your note is a synthetic preview for Day 5. Saving connects on Day 6.</p></>}
function History(){return <><section className="heading"><p className="kicker">History</p><h1>Small moments, remembered.</h1><p>Browse your notes by day. Search and editing arrive on Day 7.</p></section><section className="list">{samples.map(e=><article className="card history" key={e.date}><div>{e.date}<span>{e.tag}</span></div><p>{e.text}</p><footer>Mood · {e.mood}<span>Preview only</span></footer></article>)}</section><p className="privacy">These are synthetic entries for the interface preview.</p></>}
function Settings(){return <><section className="heading"><p className="kicker">Settings</p><h1>Your journal, your boundaries.</h1><p>Health-bee is designed to keep your data close.</p></section><section className="list">{[["⌑","Local storage","Entries will be stored in a SQLite file on this Mac.","Ready"],["✦","Local AI","Optional analysis will use a model running on this device.","Not connected"],["↗","Backups","Encrypted local backups and export controls are planned.","Coming later"]].map(([icon,title,copy,status])=><article className="card setting" key={title}><b>{icon}</b><div><h2>{title}</h2><p>{copy}</p></div><span>{status}</span></article>)}</section><p className="privacy">⌑ There is no account, analytics, or remote sync.</p></>}
function App(){const [screen,setScreen]=useState<Screen>("today");return <div className="shell"><aside><div className="brand"><b>✦</b>health-bee</div><p className="aside-copy">A quiet place to notice what your body is telling you.</p><nav><Nav active={screen==="today"} label="Today" icon="○" onClick={()=>setScreen("today")}/><Nav active={screen==="history"} label="History" icon="◷" onClick={()=>setScreen("history")}/><Nav active={screen==="settings"} label="Settings" icon="⚙" onClick={()=>setScreen("settings")}/></nav><div className="private">⌑ <span><strong>Private by design</strong>Stored on this Mac</span></div></aside><main><header className="top">Tuesday · September 30, 2026 <span>● Local only</span></header>{screen==="today"?<Today/>:screen==="history"?<History/>:<Settings/>}</main></div>}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
